use std::fs;
use std::path::Path;
use serde_json::Value;
use tetsuyu::components::cpu::cpu::Cpu;
use tetsuyu::components::mode::GBMode;
use tetsuyu::components::prelude::Registers;
use tetsuyu::hw::bus::{BusDir, Pins};
use tetsuyu::hw::interrupt::{InterruptController, Interrupts};

mod common;

pub fn run_sst_test(sub_path: &str) {
    let sst = format!("sst/v1/{sub_path}.json");
    let path = Path::new(&sst);

    if !path.exists() {
        return;
    }

    let contents = fs::read_to_string(path).unwrap();
    let json: Value = serde_json::from_str(contents.as_str()).unwrap();

    for test in json.as_array().unwrap() {
        let mut cpu = Cpu::new(GBMode::DMG);
        let mut ic = InterruptController::new();
        let mut pins = Pins::new();
        let mut ram: [u8; 0x10000] = [0; 0x10000];

        let name = test["name"].as_str().unwrap();
        let initial_state = &test["initial"];
        let final_state = &test["final"];

        cpu.reg = json_to_reg(initial_state);

        let ram_values = &initial_state["ram"].as_array().unwrap();
        for ram_val in ram_values.iter() {
            ram[ram_val[0].as_u64().unwrap() as usize] = ram_val[1].as_u64().unwrap() as u8;
        }

        let cycles = &test["cycles"].as_array().unwrap();

        for _cycle in cycles.iter() {
            m_cycle(&mut cpu, &mut ic, &mut pins, &mut ram);
        }

        cpu.run_free_acts();

        let final_reg = json_to_reg(final_state);

        let final_values = &final_state["ram"].as_array().unwrap();
        for ram_val in final_values.iter() {
            let address = ram_val[0].as_u64().unwrap() as usize;
            let value = ram_val[1].as_u64().unwrap() as u8;

            assert_eq!(ram[address], value,
                       "{}: RAM at {} was {}, expected {}", name, address, ram[address], value);
        }

        assert_eq!(cpu.reg, final_reg, "{}", name);
    }

    assert!(true);
}

fn m_cycle(cpu: &mut Cpu, ic: &mut InterruptController, mut pins: &mut Pins, ram: &mut [u8; 0x10000]) {
    let was_halted = cpu.is_halted();
    cpu.run_free_acts();

    if cpu.is_halted() {
        if ic.pending() != Interrupts::empty() {
            if !was_halted && !cpu.ime() {
                cpu.trigger_halt_bug();
            }
            cpu.wake();
        } else {
            pins.dir = BusDir::Idle;
            pins.transfer = false;
            return;
        }
    }

    if cpu.take_isr_latch() {
        let pending = ic.pending();
        if let Some(bit) = cpu.latch_isr_vector(pending) {
            ic.acknowledge(bit);
        }
    }

    cpu.setup(&mut pins);

    match pins.dir {
        BusDir::Read => {
            pins.data = ram[pins.address as usize];
        }
        BusDir::Write => {
            ram[pins.address as usize] = pins.data;
        }
        BusDir::Idle => {}
    }

    let fetched = cpu.complete(&pins);
    pins.transfer = false;

    if fetched {
        let pending = ic.pending();
        cpu.offer_interrupt(pending);
    }
}

pub fn json_to_reg(value: &Value) -> Registers {
    Registers {
        a: value["a"].as_u64().unwrap() as u8,
        f: value["f"].as_u64().unwrap() as u8,
        b: value["b"].as_u64().unwrap() as u8,
        c: value["c"].as_u64().unwrap() as u8,
        d: value["d"].as_u64().unwrap() as u8,
        e: value["e"].as_u64().unwrap() as u8,
        h: value["h"].as_u64().unwrap() as u8,
        l: value["l"].as_u64().unwrap() as u8,
        pc: value["pc"].as_u64().unwrap() as u16,
        sp: value["sp"].as_u64().unwrap() as u16,
    }
}

mod sst {
    use super::*;

    test_suite![
        run_sst_test,
        nop => ("00"),
        ld_bc_16 => ("01"),
        ld_bc => ("02"),
        inc_bc => ("03"),
        inc_b => ("04"),
        dec_b => ("05"),
        ld_b => ("06"),
        rlca => ("07"),
        ld_sp => ("08"),
        add_hl_bc => ("09"),
        ld_a_bc => ("0a"),
        dec_bc => ("0b"),
        inc_c => ("0c"),
        dec_c => ("0d"),
        ld_c => ("0e"),
        rrca => ("0f"),
        #[ignore]
        stop => ("10"),
        ld_de_16 => ("11"),
        ld_de => ("12"),
        inc_de => ("13"),
        inc_d => ("14"),
        dec_d => ("15"),
        ld_d => ("16"),
        rla => ("17"),
        jr => ("18"),
        add_hl_de => ("19"),
        ld_a_de => ("1a"),
        dec_de => ("1b"),
        inc_e => ("1c"),
        dec_e => ("1d"),
        ld_e => ("1e"),
        rra => ("1f"),
        jr_nz => ("20"),
        ld_hl_16 => ("21"),
        ld_hlp => ("22"),
        inc_hl => ("23"),
        inc_h => ("24"),
        dec_h => ("25"),
        ld_h => ("26"),
        daa => ("27"),
        jr_z => ("28"),
        add_hl_hl => ("29"),
        ld_a_hlp => ("2a"),
        dec_hl => ("2b"),
        inc_l => ("2c"),
        dec_l => ("2d"),
        ld_l => ("2e"),
        cpl => ("2f"),
        jr_nc => ("30"),
        ld_sp_16 => ("31"),
        ld_hlm => ("32"),
        inc_sp => ("33"),
        inc_hl_ind => ("34"),
        dec_hl_ind => ("35"),
        ld_hl_d8 => ("36"),
        scf => ("37"),
        jr_c => ("38"),
        add_hl_sp => ("39"),
        ld_a_hlm => ("3a"),
        dec_sp => ("3b"),
        inc_a => ("3c"),
        dec_a => ("3d"),
        ld_a => ("3e"),
        ccf => ("3f"),
        ld_b_b => ("40"),
        ld_b_c => ("41"),
        ld_b_d => ("42"),
        ld_b_e => ("43"),
        ld_b_h => ("44"),
        ld_b_l => ("45"),
        ld_b_hl => ("46"),
        ld_b_a => ("47"),
        ld_c_b => ("48"),
        ld_c_c => ("49"),
        ld_c_d => ("4a"),
        ld_c_e => ("4b"),
        ld_c_h => ("4c"),
        ld_c_l => ("4d"),
        ld_c_hl => ("4e"),
        ld_c_a => ("4f"),
        ld_d_b => ("50"),
        ld_d_c => ("51"),
        ld_d_d => ("52"),
        ld_d_e => ("53"),
        ld_d_h => ("54"),
        ld_d_l => ("55"),
        ld_d_hl => ("56"),
        ld_d_a => ("57"),
        ld_e_b => ("58"),
        ld_e_c => ("59"),
        ld_e_d => ("5a"),
        ld_e_e => ("5b"),
        ld_e_h => ("5c"),
        ld_e_l => ("5d"),
        ld_e_hl => ("5e"),
        ld_e_a => ("5f"),
        ld_h_b => ("60"),
        ld_h_c => ("61"),
        ld_h_d => ("62"),
        ld_h_e => ("63"),
        ld_h_h => ("64"),
        ld_h_l => ("65"),
        ld_h_hl => ("66"),
        ld_h_a => ("67"),
        ld_l_b => ("68"),
        ld_l_c => ("69"),
        ld_l_d => ("6a"),
        ld_l_e => ("6b"),
        ld_l_h => ("6c"),
        ld_l_l => ("6d"),
        ld_l_hl => ("6e"),
        ld_l_a => ("6f"),
        ld_hl_b => ("70"),
        ld_hl_c => ("71"),
        ld_hl_d => ("72"),
        ld_hl_e => ("73"),
        ld_hl_h => ("74"),
        ld_hl_l => ("75"),
        halt => ("76"),
        ld_hl_a => ("77"),
        ld_a_b => ("78"),
        ld_a_c => ("79"),
        ld_a_d => ("7a"),
        ld_a_e => ("7b"),
        ld_a_h => ("7c"),
        ld_a_l => ("7d"),
        ld_a_hl => ("7e"),
        ld_a_a => ("7f"),
        add_a_b => ("80"),
        add_a_c => ("81"),
        add_a_d => ("82"),
        add_a_e => ("83"),
        add_a_h => ("84"),
        add_a_l => ("85"),
        add_a_hl => ("86"),
        add_a_a => ("87"),
        adc_a_b => ("88"),
        adc_a_c => ("89"),
        adc_a_d => ("8a"),
        adc_a_e => ("8b"),
        adc_a_h => ("8c"),
        adc_a_l => ("8d"),
        adc_a_hl => ("8e"),
        adc_a_a => ("8f"),
        sub_b => ("90"),
        sub_c => ("91"),
        sub_d => ("92"),
        sub_e => ("93"),
        sub_h => ("94"),
        sub_l => ("95"),
        sub_hl => ("96"),
        sub_a => ("97"),
        sbc_a_b => ("98"),
        sbc_a_c => ("99"),
        sbc_a_d => ("9a"),
        sbc_a_e => ("9b"),
        sbc_a_h => ("9c"),
        sbc_a_l => ("9d"),
        sbc_a_hl => ("9e"),
        sbc_a_a => ("9f"),
        and_b => ("a0"),
        and_c => ("a1"),
        and_d => ("a2"),
        and_e => ("a3"),
        and_h => ("a4"),
        and_l => ("a5"),
        and_hl => ("a6"),
        and_a => ("a7"),
        xor_b => ("a8"),
        xor_c => ("a9"),
        xor_d => ("aa"),
        xor_e => ("ab"),
        xor_h => ("ac"),
        xor_l => ("ad"),
        xor_hl => ("ae"),
        xor_a => ("af"),
        or_b => ("b0"),
        or_c => ("b1"),
        or_d => ("b2"),
        or_e => ("b3"),
        or_h => ("b4"),
        or_l => ("b5"),
        or_hl => ("b6"),
        or_a => ("b7"),
        cp_b => ("b8"),
        cp_c => ("b9"),
        cp_d => ("ba"),
        cp_e => ("bb"),
        cp_h => ("bc"),
        cp_l => ("bd"),
        cp_hl => ("be"),
        cp_a => ("bf"),
        ret_nz => ("c0"),
        pop_bc => ("c1"),
        jp_nz => ("c2"),
        jp => ("c3"),
        call_nz => ("c4"),
        push_bc => ("c5"),
        add_a_d8 => ("c6"),
        rst_00 => ("c7"),
        ret_z => ("c8"),
        ret => ("c9"),
        jp_z => ("ca"),
        call_z => ("cc"),
        call => ("cd"),
        adc_a_d8 => ("ce"),
        rst_08 => ("cf"),
        ret_nc => ("d0"),
        pop_de => ("d1"),
        jp_nc => ("d2"),
        call_nc => ("d4"),
        push_de => ("d5"),
        sub_d8 => ("d6"),
        rst_10 => ("d7"),
        ret_c => ("d8"),
        reti => ("d9"),
        jp_c => ("da"),
        call_c => ("dc"),
        sbc_a_d8 => ("de"),
        rst_18 => ("df"),
        ldh_a8 => ("e0"),
        pop_hl => ("e1"),
        ldh_c => ("e2"),
        push_hl => ("e5"),
        and_d8 => ("e6"),
        rst_20 => ("e7"),
        add_sp_r8 => ("e8"),
        jp_hl => ("e9"),
        ld_a16_a => ("ea"),
        xor_d8 => ("ee"),
        rst_28 => ("ef"),
        ldh_a_a8 => ("f0"),
        pop_af => ("f1"),
        ldh_a_c => ("f2"),
        di => ("f3"),
        push_af => ("f5"),
        or_d8 => ("f6"),
        rst_30 => ("f7"),
        ld_hl_sp_r8 => ("f8"),
        ld_sp_hl => ("f9"),
        ld_a_a16 => ("fa"),
        ei => ("fb"),
        cp_d8 => ("fe"),
        rst_38 => ("ff"),
        cb_rlc_b => ("cb 00"),
        cb_rlc_c => ("cb 01"),
        cb_rlc_d => ("cb 02"),
        cb_rlc_e => ("cb 03"),
        cb_rlc_h => ("cb 04"),
        cb_rlc_l => ("cb 05"),
        cb_rlc_hl => ("cb 06"),
        cb_rlc_a => ("cb 07"),
        cb_rrc_b => ("cb 08"),
        cb_rrc_c => ("cb 09"),
        cb_rrc_d => ("cb 0a"),
        cb_rrc_e => ("cb 0b"),
        cb_rrc_h => ("cb 0c"),
        cb_rrc_l => ("cb 0d"),
        cb_rrc_hl => ("cb 0e"),
        cb_rrc_a => ("cb 0f"),
        cb_rl_b => ("cb 10"),
        cb_rl_c => ("cb 11"),
        cb_rl_d => ("cb 12"),
        cb_rl_e => ("cb 13"),
        cb_rl_h => ("cb 14"),
        cb_rl_l => ("cb 15"),
        cb_rl_hl => ("cb 16"),
        cb_rl_a => ("cb 17"),
        cb_rr_b => ("cb 18"),
        cb_rr_c => ("cb 19"),
        cb_rr_d => ("cb 1a"),
        cb_rr_e => ("cb 1b"),
        cb_rr_h => ("cb 1c"),
        cb_rr_l => ("cb 1d"),
        cb_rr_hl => ("cb 1e"),
        cb_rr_a => ("cb 1f"),
        cb_sla_b => ("cb 20"),
        cb_sla_c => ("cb 21"),
        cb_sla_d => ("cb 22"),
        cb_sla_e => ("cb 23"),
        cb_sla_h => ("cb 24"),
        cb_sla_l => ("cb 25"),
        cb_sla_hl => ("cb 26"),
        cb_sla_a => ("cb 27"),
        cb_sra_b => ("cb 28"),
        cb_sra_c => ("cb 29"),
        cb_sra_d => ("cb 2a"),
        cb_sra_e => ("cb 2b"),
        cb_sra_h => ("cb 2c"),
        cb_sra_l => ("cb 2d"),
        cb_sra_hl => ("cb 2e"),
        cb_sra_a => ("cb 2f"),
        cb_swap_b => ("cb 30"),
        cb_swap_c => ("cb 31"),
        cb_swap_d => ("cb 32"),
        cb_swap_e => ("cb 33"),
        cb_swap_h => ("cb 34"),
        cb_swap_l => ("cb 35"),
        cb_swap_hl => ("cb 36"),
        cb_swap_a => ("cb 37"),
        cb_srl_b => ("cb 38"),
        cb_srl_c => ("cb 39"),
        cb_srl_d => ("cb 3a"),
        cb_srl_e => ("cb 3b"),
        cb_srl_h => ("cb 3c"),
        cb_srl_l => ("cb 3d"),
        cb_srl_hl => ("cb 3e"),
        cb_srl_a => ("cb 3f"),
        cb_bit_0_b => ("cb 40"),
        cb_bit_0_c => ("cb 41"),
        cb_bit_0_d => ("cb 42"),
        cb_bit_0_e => ("cb 43"),
        cb_bit_0_h => ("cb 44"),
        cb_bit_0_l => ("cb 45"),
        cb_bit_0_hl => ("cb 46"),
        cb_bit_0_a => ("cb 47"),
        cb_bit_1_b => ("cb 48"),
        cb_bit_1_c => ("cb 49"),
        cb_bit_1_d => ("cb 4a"),
        cb_bit_1_e => ("cb 4b"),
        cb_bit_1_h => ("cb 4c"),
        cb_bit_1_l => ("cb 4d"),
        cb_bit_1_hl => ("cb 4e"),
        cb_bit_1_a => ("cb 4f"),
        cb_bit_2_b => ("cb 50"),
        cb_bit_2_c => ("cb 51"),
        cb_bit_2_d => ("cb 52"),
        cb_bit_2_e => ("cb 53"),
        cb_bit_2_h => ("cb 54"),
        cb_bit_2_l => ("cb 55"),
        cb_bit_2_hl => ("cb 56"),
        cb_bit_2_a => ("cb 57"),
        cb_bit_3_b => ("cb 58"),
        cb_bit_3_c => ("cb 59"),
        cb_bit_3_d => ("cb 5a"),
        cb_bit_3_e => ("cb 5b"),
        cb_bit_3_h => ("cb 5c"),
        cb_bit_3_l => ("cb 5d"),
        cb_bit_3_hl => ("cb 5e"),
        cb_bit_3_a => ("cb 5f"),
        cb_bit_4_b => ("cb 60"),
        cb_bit_4_c => ("cb 61"),
        cb_bit_4_d => ("cb 62"),
        cb_bit_4_e => ("cb 63"),
        cb_bit_4_h => ("cb 64"),
        cb_bit_4_l => ("cb 65"),
        cb_bit_4_hl => ("cb 66"),
        cb_bit_4_a => ("cb 67"),
        cb_bit_5_b => ("cb 68"),
        cb_bit_5_c => ("cb 69"),
        cb_bit_5_d => ("cb 6a"),
        cb_bit_5_e => ("cb 6b"),
        cb_bit_5_h => ("cb 6c"),
        cb_bit_5_l => ("cb 6d"),
        cb_bit_5_hl => ("cb 6e"),
        cb_bit_5_a => ("cb 6f"),
        cb_bit_6_b => ("cb 70"),
        cb_bit_6_c => ("cb 71"),
        cb_bit_6_d => ("cb 72"),
        cb_bit_6_e => ("cb 73"),
        cb_bit_6_h => ("cb 74"),
        cb_bit_6_l => ("cb 75"),
        cb_bit_6_hl => ("cb 76"),
        cb_bit_6_a => ("cb 77"),
        cb_bit_7_b => ("cb 78"),
        cb_bit_7_c => ("cb 79"),
        cb_bit_7_d => ("cb 7a"),
        cb_bit_7_e => ("cb 7b"),
        cb_bit_7_h => ("cb 7c"),
        cb_bit_7_l => ("cb 7d"),
        cb_bit_7_hl => ("cb 7e"),
        cb_bit_7_a => ("cb 7f"),
        cb_res_0_b => ("cb 80"),
        cb_res_0_c => ("cb 81"),
        cb_res_0_d => ("cb 82"),
        cb_res_0_e => ("cb 83"),
        cb_res_0_h => ("cb 84"),
        cb_res_0_l => ("cb 85"),
        cb_res_0_hl => ("cb 86"),
        cb_res_0_a => ("cb 87"),
        cb_res_1_b => ("cb 88"),
        cb_res_1_c => ("cb 89"),
        cb_res_1_d => ("cb 8a"),
        cb_res_1_e => ("cb 8b"),
        cb_res_1_h => ("cb 8c"),
        cb_res_1_l => ("cb 8d"),
        cb_res_1_hl => ("cb 8e"),
        cb_res_1_a => ("cb 8f"),
        cb_res_2_b => ("cb 90"),
        cb_res_2_c => ("cb 91"),
        cb_res_2_d => ("cb 92"),
        cb_res_2_e => ("cb 93"),
        cb_res_2_h => ("cb 94"),
        cb_res_2_l => ("cb 95"),
        cb_res_2_hl => ("cb 96"),
        cb_res_2_a => ("cb 97"),
        cb_res_3_b => ("cb 98"),
        cb_res_3_c => ("cb 99"),
        cb_res_3_d => ("cb 9a"),
        cb_res_3_e => ("cb 9b"),
        cb_res_3_h => ("cb 9c"),
        cb_res_3_l => ("cb 9d"),
        cb_res_3_hl => ("cb 9e"),
        cb_res_3_a => ("cb 9f"),
        cb_res_4_b => ("cb a0"),
        cb_res_4_c => ("cb a1"),
        cb_res_4_d => ("cb a2"),
        cb_res_4_e => ("cb a3"),
        cb_res_4_h => ("cb a4"),
        cb_res_4_l => ("cb a5"),
        cb_res_4_hl => ("cb a6"),
        cb_res_4_a => ("cb a7"),
        cb_res_5_b => ("cb a8"),
        cb_res_5_c => ("cb a9"),
        cb_res_5_d => ("cb aa"),
        cb_res_5_e => ("cb ab"),
        cb_res_5_h => ("cb ac"),
        cb_res_5_l => ("cb ad"),
        cb_res_5_hl => ("cb ae"),
        cb_res_5_a => ("cb af"),
        cb_res_6_b => ("cb b0"),
        cb_res_6_c => ("cb b1"),
        cb_res_6_d => ("cb b2"),
        cb_res_6_e => ("cb b3"),
        cb_res_6_h => ("cb b4"),
        cb_res_6_l => ("cb b5"),
        cb_res_6_hl => ("cb b6"),
        cb_res_6_a => ("cb b7"),
        cb_res_7_b => ("cb b8"),
        cb_res_7_c => ("cb b9"),
        cb_res_7_d => ("cb ba"),
        cb_res_7_e => ("cb bb"),
        cb_res_7_h => ("cb bc"),
        cb_res_7_l => ("cb bd"),
        cb_res_7_hl => ("cb be"),
        cb_res_7_a => ("cb bf"),
        cb_set_0_b => ("cb c0"),
        cb_set_0_c => ("cb c1"),
        cb_set_0_d => ("cb c2"),
        cb_set_0_e => ("cb c3"),
        cb_set_0_h => ("cb c4"),
        cb_set_0_l => ("cb c5"),
        cb_set_0_hl => ("cb c6"),
        cb_set_0_a => ("cb c7"),
        cb_set_1_b => ("cb c8"),
        cb_set_1_c => ("cb c9"),
        cb_set_1_d => ("cb ca"),
        cb_set_1_e => ("cb cb"),
        cb_set_1_h => ("cb cc"),
        cb_set_1_l => ("cb cd"),
        cb_set_1_hl => ("cb ce"),
        cb_set_1_a => ("cb cf"),
        cb_set_2_b => ("cb d0"),
        cb_set_2_c => ("cb d1"),
        cb_set_2_d => ("cb d2"),
        cb_set_2_e => ("cb d3"),
        cb_set_2_h => ("cb d4"),
        cb_set_2_l => ("cb d5"),
        cb_set_2_hl => ("cb d6"),
        cb_set_2_a => ("cb d7"),
        cb_set_3_b => ("cb d8"),
        cb_set_3_c => ("cb d9"),
        cb_set_3_d => ("cb da"),
        cb_set_3_e => ("cb db"),
        cb_set_3_h => ("cb dc"),
        cb_set_3_l => ("cb dd"),
        cb_set_3_hl => ("cb de"),
        cb_set_3_a => ("cb df"),
        cb_set_4_b => ("cb e0"),
        cb_set_4_c => ("cb e1"),
        cb_set_4_d => ("cb e2"),
        cb_set_4_e => ("cb e3"),
        cb_set_4_h => ("cb e4"),
        cb_set_4_l => ("cb e5"),
        cb_set_4_hl => ("cb e6"),
        cb_set_4_a => ("cb e7"),
        cb_set_5_b => ("cb e8"),
        cb_set_5_c => ("cb e9"),
        cb_set_5_d => ("cb ea"),
        cb_set_5_e => ("cb eb"),
        cb_set_5_h => ("cb ec"),
        cb_set_5_l => ("cb ed"),
        cb_set_5_hl => ("cb ee"),
        cb_set_5_a => ("cb ef"),
        cb_set_6_b => ("cb f0"),
        cb_set_6_c => ("cb f1"),
        cb_set_6_d => ("cb f2"),
        cb_set_6_e => ("cb f3"),
        cb_set_6_h => ("cb f4"),
        cb_set_6_l => ("cb f5"),
        cb_set_6_hl => ("cb f6"),
        cb_set_6_a => ("cb f7"),
        cb_set_7_b => ("cb f8"),
        cb_set_7_c => ("cb f9"),
        cb_set_7_d => ("cb fa"),
        cb_set_7_e => ("cb fb"),
        cb_set_7_h => ("cb fc"),
        cb_set_7_l => ("cb fd"),
        cb_set_7_hl => ("cb fe"),
        cb_set_7_a => ("cb ff"),
    ];
}
